/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.eulen.actividades.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActividadesEspeciales service. Represents a row in the &quot;EULEN_ActividadesEspeciales&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.eulen.actividades.service.model.impl.ActividadesEspecialesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.eulen.actividades.service.model.impl.ActividadesEspecialesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActividadesEspeciales
 * @see com.eulen.actividades.service.model.impl.ActividadesEspecialesImpl
 * @see com.eulen.actividades.service.model.impl.ActividadesEspecialesModelImpl
 * @generated
 */
@ProviderType
public interface ActividadesEspecialesModel extends BaseModel<ActividadesEspeciales> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a actividades especiales model instance should use the {@link ActividadesEspeciales} interface instead.
	 */

	/**
	 * Returns the primary key of this actividades especiales.
	 *
	 * @return the primary key of this actividades especiales
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this actividades especiales.
	 *
	 * @param primaryKey the primary key of this actividades especiales
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this actividades especiales.
	 *
	 * @return the uuid of this actividades especiales
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this actividades especiales.
	 *
	 * @param uuid the uuid of this actividades especiales
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the actividad ID of this actividades especiales.
	 *
	 * @return the actividad ID of this actividades especiales
	 */
	public long getActividadId();

	/**
	 * Sets the actividad ID of this actividades especiales.
	 *
	 * @param actividadId the actividad ID of this actividades especiales
	 */
	public void setActividadId(long actividadId);

	/**
	 * Returns the group ID of this actividades especiales.
	 *
	 * @return the group ID of this actividades especiales
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this actividades especiales.
	 *
	 * @param groupId the group ID of this actividades especiales
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this actividades especiales.
	 *
	 * @return the user ID of this actividades especiales
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this actividades especiales.
	 *
	 * @param userId the user ID of this actividades especiales
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this actividades especiales.
	 *
	 * @return the user uuid of this actividades especiales
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this actividades especiales.
	 *
	 * @param userUuid the user uuid of this actividades especiales
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this actividades especiales.
	 *
	 * @return the create date of this actividades especiales
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this actividades especiales.
	 *
	 * @param createDate the create date of this actividades especiales
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the text of this actividades especiales.
	 *
	 * @return the text of this actividades especiales
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this actividades especiales.
	 *
	 * @param text the text of this actividades especiales
	 */
	public void setText(String text);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ActividadesEspeciales actividadesEspeciales);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ActividadesEspeciales> toCacheModel();

	@Override
	public ActividadesEspeciales toEscapedModel();

	@Override
	public ActividadesEspeciales toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}